# Generated by Django 4.0.5 on 2022-06-09 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autoExtractApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='request_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
